import imageIpad from './assets/ipad-dorso-anverso.svg';
import imageAmazon from './assets/tablet-amazon.svg';
import imageGoogle from './assets/tablet-google.svg';
import imageHuawei from './assets/tablet-huawei.svg';
import imageLenovo from './assets/tablet-lenovo.svg';
import imageMicrosoft from './assets/tablet-microsoft.svg';
import imageSamsung from './assets/tablet-samsung-anverso-dorso.svg';

const data = [
  {
  id: 1,
  price: 1099,
  isActive: true,
  category: null,
  model: "iPad Pro",
  processor: "Apple M1",
  screen: "12.9 inches",
  hardcore: "256GB",
  usetype: null,
  Ram: "8GB",
  videoCard: "Apple M1",
  operatingSystem: "iPadOS",
  dimensions: "28.06 x 21.49 x 0.59 cm",
  weight: null,
  batteryLife: "Up to 10 hours",
  connectivity: "Wi-Fi, Bluetooth",
  warranty: "12 months",
  description: "The iPad Pro offers a seamless user experience with its sleek design and intuitive interface. Its large 12.9-inch display provides vibrant visuals, while the powerful M1 processor ensures smooth performance for all tasks. With up to 10 hours of battery life, it's perfect for work or entertainment on the go.",
  internalmemory: null,
  camera: null,
  sound: null,
  compatibility: null,
  extrafunctions: null,
  waterproof: null,
  touchControl: null,
  microphone: null,
  lights: null,
  design: null,
  keycapDesign: null,
  mediaKeys: null,
  wirelessRange: null,
  createdAt: "2024-02-17T15:08:19.394Z",
  updatedAt: "2024-02-17T15:08:19.394Z",
    image: imageIpad,
  },
  {
    id: 2,
    category: "tablet",
    model: "Samsung Galaxy Tab S7+",
    processor: "Qualcomm Snapdragon 865+",
    screen: "12.4 inches",
    hardcore: "256GB",
    "use-type": "Tablet",
    Ram: "8GB",
    "video-card": "Adreno 650",
    price: "$849",
    "operating-sistem": "Android",
    dimensions: "28.6 x 18.5 x 0.59 cm",
    weight: "575 grams",
    "battery-life": "Up to 14 hours",
    connectivity: "Wi-Fi, Bluetooth",
    warranty: "12 months",
    description: "The Samsung Galaxy Tab S7+ is designed for users seeking a premium tablet experience. With its large, high-quality display and powerful performance, it's perfect for professionals, creatives, and multimedia enthusiasts. The included S Pen stylus enhances productivity and creativity, making it an ideal choice for those who need versatility on the go.",
    image: imageSamsung
  },
  {
      id: 3,
      category: "tablet",
      model: "Microsoft Surface Pro 8",
      processor: "11th Gen Intel Core i5",
      screen: "13 inches",
      hardcore: "256GB",
      "use-type": "Tablet",
      Ram: "8GB",
      "video-card": "Intel Iris Xe Graphics",
      price: "$999",
      "operating-sistem": "Windows 11",
      dimensions: "29.21 x 20.07 x 0.84 cm",
      weight: "770 grams",
      "battery-life": "Up to 16 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Microsoft Surface Pro 8 offers a versatile computing experience tailored for productivity-focused users. Its sleek design and powerful performance make it ideal for professionals, students, and creatives who need a portable yet capable device. With its detachable keyboard and touch screen functionality, it seamlessly transitions between laptop and tablet modes, catering to a variety of work styles.",
      image: imageMicrosoft
    },
    {
      id: 4,
      category: "tablet",
      model: "Lenovo Tab P11 Pro",
      processor: "Qualcomm Snapdragon 870",
      screen: "11.5 inches",
      hardcore: "128GB",
      "use-type": "Tablet",
      Ram: "6GB",
      "video-card": "Adreno 650",
      price: "$499",
      "operating-sistem": "Android",
      dimensions: "26.7 x 17.1 x 0.56 cm",
      weight: "485 grams",
      "battery-life": "Up to 15 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Lenovo Tab P11 Pro is designed for users seeking a balance of productivity and entertainment. With its sleek design and powerful performance, it's perfect for both work and play. The tablet's vibrant display and long battery life make it great for multimedia consumption, while its productivity features cater to users who need to get things done on the go. Whether you're streaming content, browsing the web, or working on documents, the Tab P11 Pro offers a versatile and enjoyable experience.",
      image: imageLenovo
    },
    {
      id: 5,
      category: "tablet",
      model: "Huawei MatePad Pro",
      processor: "HiSilicon Kirin 9000E",
      screen: "12.6 inches",
      hardcore: "256GB",
      "use-type": "Tablet",
      Ram: "8GB",
      "video-card": "Mali-G78 MP24",
      price: "$799",
      "operating-sistem": "HarmonyOS",
      dimensions: "28.5 x 18.5 x 0.64 cm",
      weight: "609 grams",
      "battery-life": "Up to 10 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Lenovo Tab P11 Pro offers a sleek design, powerful performance, and long battery life, making it perfect for both work and entertainment. With its vibrant display and productivity features, it's ideal for users on the go seeking a versatile experience.",
      image: imageHuawei
    },
    {
      id: 6,
      category: "tablet",
      model: "Amazon Fire HD 10",
      processor: "Octa-core 2.0 GHz",
      screen: "10.1 inches",
      hardcore: "32GB",
      "use-type": "Tablet",
      Ram: "3GB",
      "video-card": "PowerVR GM9446",
      price: "$149",
      "operating-sistem": "Fire OS",
      dimensions: "26.3 x 15.9 x 0.93 cm",
      weight: "465 grams",
      "battery-life": "Up to 12 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Amazon Fire HD 10 is a budget-friendly tablet ideal for casual users who enjoy multimedia content and basic app usage. With its 10.1-inch display and long battery life, it's perfect for streaming, browsing, and reading. Running on Fire OS, it provides access to various apps and entertainment through the Amazon Appstore.",
      image: imageAmazon
    },
    {
      id: 7,
      category: "tablet",
      model: "Google Pixel Slate",
      processor: "8th Gen Intel Core i5",
      screen: "12.3 inches",
      hardcore: "128GB",
      "use-type": "Tablet",
      Ram: "8GB",
      "video-card": "Intel UHD Graphics 615",
      price: "$799",
      "operating-sistem": "Chrome OS",
      dimensions: "29.2 x 20.3 x 0.72 cm",
      weight: "721 grams",
      "battery-life": "Up to 10 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Google Pixel Slate is a versatile tablet designed for users who prioritize productivity and entertainment. With its 12.3-inch display and powerful performance, it's perfect for multitasking and creativity. Running on Chrome OS, it offers access to a wide range of apps and services from the Google ecosystem. Whether you're working on documents, streaming content, or browsing the web, the Pixel Slate delivers a seamless and intuitive user experience.",
      image: imageGoogle
    },
    {
      id: 8,
      category: "tablet",
      model: "Sony Xperia Z4 Tablet",
      processor: "Qualcomm Snapdragon 810",
      screen: "10.1 inches",
      hardcore: "32GB",
      "use-type": "Tablet",
      Ram: "3GB",
      "video-card": "Adreno 430",
      price: "$499",
      "operating-sistem": "Android",
      dimensions: "25.6 x 16.9 x 0.63 cm",
      weight: "393 grams",
      "battery-life": "Up to 17 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Sony Xperia Z4 Tablet combines sleek design with powerful performance, perfect for on-the-go entertainment and productivity."
    },
    {
      id: 9,
      category: "tablet",
      model: "Asus ZenPad 3S 10",
      processor: "Hexa-core 2.1 GHz",
      screen: "9.7 inches",
      hardcore: "64GB",
      "use-type": "Tablet",
      Ram: "4GB",
      "video-card": "PowerVR GX6250",
      price: "$329",
      "operating-sistem": "Android",
      dimensions: "24.7 x 16.9 x 0.57 cm",
      weight: "430 grams",
      "battery-life": "Up to 10 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Asus ZenPad 3S 10 offers a sleek and lightweight design, making it ideal for users who prioritize portability. With its crisp display and smooth performance, it's perfect for multimedia consumption and light productivity tasks on the go."
    },
    {
      id: 10,
      category: "tablet",
      model: "Xiaomi Mi Pad 5",
      processor: "Qualcomm Snapdragon 860",
      screen: "11 inches",
      hardcore: "128GB",
      "use-type": "Tablet",
      Ram: "6GB",
      "video-card": "Adreno 640",
      price: "$399",
      "operating-sistem": "MIUI",
      dimensions: "25.8 x 16.9 x 0.69 cm",
      weight: "511 grams",
      "battery-life": "Up to 12 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Xiaomi Mi Pad 5 is tailored for users seeking a blend of performance and affordability. With its spacious display and powerful hardware, it's ideal for multimedia enthusiasts and casual gamers. The tablet's sleek design and long battery life ensure a satisfying user experience for entertainment and productivity tasks alike."
    },
    {
      id: 11,
      category: "tablet",
      model: "HP Elite x2 G8",
      processor: "11th Gen Intel Core i5",
      screen: "13 inches",
      hardcore: "256GB",
      "use-type": "Tablet",
      Ram: "8GB",
      "video-card": "Intel Iris Xe Graphics",
      price: "$1299",
      "operating-sistem": "Windows 11",
      dimensions: "29.21 x 20.07 x 0.84 cm",
      weight: "820 grams",
      "battery-life": "Up to 16 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The HP Elite x2 G8 is a premium tablet tailored for business professionals who demand performance and versatility. With its sleek design, robust security features, and long battery life, it's perfect for on-the-go productivity and collaboration."
    },
    {
      id: 12,
      category: "tablet",
      model: "Razer Book 13",
      processor: "11th Gen Intel Core i5",
      screen: "13.4 inches",
      hardcore: "256GB",
      "use-type": "Tablet",
      Ram: "8GB",
      "video-card": "Intel Iris Xe Graphics",
      price: "$1199",
      "operating-sistem": "Windows 11",
      dimensions: "28.1 x 19.5 x 1.5 cm",
      weight: "1395 grams",
      "battery-life": "Up to 14 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Razer Book 13 is a stylish and high-performance laptop designed"
    },
    {
      id: 13,
      category: "tablet",
      model: "Dell Latitude 7320",
      processor: "11th Gen Intel Core i5",
      screen: "13 inches",
      hardcore: "256GB",
      "use-type": "Tablet",
      Ram: "8GB",
      "video-card": "Intel Iris Xe Graphics",
      price: "$1699",
      "operating-sistem": "Windows 11",
      dimensions: "28.12 x 19.2 x 1.47 cm",
      weight: "1048 grams",
      "battery-life": "Up to 14 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Dell Latitude 7320 is a versatile and powerful tablet designed for professionals on the go. With its high-performance hardware, crisp display, and long-lasting battery, it's ideal for productivity tasks and business applications."
    },
    {
      id: 14,
      category: "tablet",
      model: "Acer Chromebook Tab 10",
      processor: "OP1 Hexa-core",
      screen: "9.7 inches",
      hardcore: "32GB",
      "use-type": "Tablet",
      Ram: "4GB",
      "video-card": "PowerVR GX6250",
      price: "$329",
      "operating-sistem": "Chrome OS",
      dimensions: "23.9 x 17.1 x 0.99 cm",
      weight: "544 grams",
      "battery-life": "Up to 9 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The Acer Chromebook Tab 10 is ideal for students and educators alike, offering a versatile and portable solution for learning and collaboration. With its lightweight design and durable construction, it's perfect for use in classrooms or on the move. The Chrome OS provides seamless access to educational apps and resources, while the included stylus enhances productivity and creativity."
    },
    {
      id: 15,
      category: "tablet",
      model: "LG G Pad 5 10.1",
      processor: "Qualcomm Snapdragon 821",
      screen: "10.1 inches",
      hardcore: "32GB",
      "use-type": "Tablet",
      Ram: "4GB",
      "video-card": "Adreno 530",
      price: "$299",
      "operating-sistem": "Android",
      dimensions: "24.89 x 15.96 x 0.82 cm",
      weight: "498 grams",
      "battery-life": "Up to 10 hours",
      connectivity: "Wi-Fi, Bluetooth",
      warranty: "12 months",
      description: "The LG G Pad 5 10.1 is crafted for users who prioritize portability and versatility. Its compact design and lightweight build make it perfect for on-the-go use, whether for work or entertainment. With a vibrant display and reliable performance, it offers a seamless experience for browsing, streaming, and light productivity tasks."
    },
    {
      id: 16,
      category: "laptop",
      model: "HP Spectre x360",
      processor: "Intel Core i7",
      ram: "16GB",
      "video-card": "Intel Iris Xe Graphics",
      "operating-sistem": "Windows 10",
      dimensions: "30.6 x 19.45 x 1.69 cm",
      weight: "1.34 kg",
      "battery-life": "Up to 15 hours",
      screen: "13.3-inch FHD Touchscreen",
      warranty: "12 months",
      hardcore: "512GB",
      description: "The HP Spectre x360 is a powerful and versatile laptop that offers a sleek design and impressive performance.",
      price: "$2.299"
    },
    {
      id: 17,
      category: "laptop",
      model: "Dell XPS 13",
      processor: "Intel Core i5",
      ram: "8GB",
      "video-card": "Intel UHD Graphics",
      "operating-sistem": "Windows 10",
      dimensions: "29.5 x 19.5 x 1.4 cm",
      weight: "1.27 kg",
      "battery-life": "Up to 12 hours",
      screen: "13.4-inch FHD+ InfinityEdge",
      warranty: "12 months",
      hardcore: "256GB",
      description: "The Dell XPS 13 is a compact and lightweight laptop that delivers a seamless user experience.",
      price: "$1.299"
    },
    {
      id: 18,
      category: "laptop",
      model: "MacBook Pro",
      processor: "Apple M1 chip",
      ram: "8GB",
      "video-card": "Apple M1 chip",
      "operating-sistem": "macOS",
      dimensions: "30.41 x 21.24 x 1.56 cm",
      weight: "1.4 kg",
      "battery-life": "Up to 20 hours",
      screen: "13.3-inch Retina display",
      warranty: "12 months",
      hardcore: "256GB",
      description: "The MacBook Pro is a high-performance laptop that offers exceptional speed and power.",
      price: "$1.199"
    },
    {
      id: 19,
      category: "laptop",
      model: "Lenovo ThinkPad X1 Carbon",
      processor: "Intel Core i7",
      ram: "16GB",
      "video-card": "Intel UHD Graphics",
      "operating-sistem": "Windows 10",
      dimensions: "31.6 x 21.7 x 1.45 cm",
      weight: "1.13 kg",
      "battery-life": "Up to 19.5 hours",
      screen: "14-inch FHD display",
      warranty: "12 months",
      hardcore: "512GB",
      description: "The Lenovo ThinkPad X1 Carbon is a durable and lightweight laptop that is perfect for business professionals.",
      price: "$1.599"
    },
    {
      id: 20,
      category: "laptop",
      model: "Asus ROG Zephyrus G14",
      processor: "AMD Ryzen 9",
      ram: "16GB",
      "video-card": "NVIDIA GeForce RTX 3060",
      "operating-sistem": "Windows 10",
      dimensions: "32.4 x 22.2 x 1.99 cm",
      weight: "1.7 kg",
      "battery-life": "Up to 10 hours",
      screen: "14-inch WQHD display",
      warranty: "12 months",
      hardcore: "1TB",
      description: "The Asus ROG Zephyrus G14 is a gaming laptop that offers powerful performance and a stunning display.",
      price: "$1.999"
    },
    {
      id: 21,
      category: "laptop",
      model: "Acer Swift 3",
      processor: "Intel Core i5",
      ram: "8GB",
      "video-card": "Intel UHD Graphics",
      "operating-sistem": "Windows 10",
      dimensions: "30.4 x 20.3 x 1.59 cm",
      weight: "1.19 kg",
      "battery-life": "Up to 16 hours",
      screen: "13.5-inch QHD display",
      warranty: "12 months",
      hardcore: "512GB",
      description: "The Acer Swift 3 is a budget-friendly laptop that delivers reliable performance and long battery life.",
      price: "$699"
    },
    {
      id: 22,
      category: "laptop",
      model: "Microsoft Surface Laptop 4",
      processor: "AMD Ryzen 7",
      ram: "16GB",
      "video-card": "AMD Radeon Graphics",
      "operating-sistem": "Windows 10",
      dimensions: "30.8 x 22.3 x 1.48 cm",
      weight: "1.27 kg",
      "battery-life": "Up to 17 hours",
      screen: "15-inch PixelSense display",
      warranty: "12 months",
      hardcore: "512GB",
      description: "The Microsoft Surface Laptop 4 is a stylish and versatile laptop that is ideal for productivity and entertainment.",
      price: "$1799"
    },
    {
      id: 23,
      category: "laptop",
      model: "Razer Blade 15",
      processor: "Intel Core i7",
      ram: "16GB",
      "video-card": "NVIDIA GeForce RTX 3070",
      "operating-sistem": "Windows 10",
      dimensions: "35.5 x 23.5 x 1.78 cm",
      weight: "2.09 kg",
      "battery-life": "Up to 6 hours",
      screen: "15.6-inch QHD display",
      warranty: "12 months",
      hardcore: "1TB",
      description: "The Razer Blade 15 is a high-performance gaming laptop that offers stunning visuals and smooth gameplay.",
      price: "$2299"
    },
    {
      id: 24,
      category: "laptop",
      model: "HP Envy x360",
      processor: "AMD Ryzen 5",
      ram: "8GB",
      "video-card": "AMD Radeon Graphics",
      "operating-sistem": "Windows 10",
      dimensions: "32.4 x 22.1 x 1.8 cm",
      weight: "1.34 kg",
      "battery-life": "Up to 12 hours",
      screen: "15.6-inch FHD Touchscreen",
      warranty: "12 months",
      hardcore: "256GB",
      description: "The HP Envy x360 is a versatile and affordable laptop that is perfect for everyday use.",
      price: "$1899"
    },
    {
      id: 25,
      category: "laptop",
      model: "Dell Inspiron 15",
      processor: "Intel Core i3",
      ram: "4GB",
      "video-card": "Intel UHD Graphics",
      "operating-sistem": "Windows 10",
      dimensions: "36.3 x 24.9 x 2.02 cm",
      weight: "1.83 kg",
      "battery-life": "Up to 7 hours",
      screen: "15.6-inch HD display",
      warranty: "12 months",
      hardcore: "256GB",
      description: "The Dell Inspiron 15 is a budget-friendly laptop that offers reliable performance and a large display.",
      price: "$1879"
    },
    {
      id: 26,
      category: "laptop",
      model: "Lenovo Yoga C940",
      processor: "Intel Core i7",
      ram: "12GB",
      "video-card": "Intel UHD Graphics",
      "operating-sistem": "Windows 10",
      dimensions: "32.2 x 21.0 x 1.45 cm",
      weight: "1.35 kg",
      "battery-life": "Up to 17.5 hours",
      screen: "14-inch FHD Touchscreen",
      warranty: "12 months",
      hardcore: "512GB",
      description: "The Lenovo Yoga C940 is a 2-in-1 laptop that combines power and versatility in a sleek and portable design.",
      price: "$1299"
    },
    {
      id: 27,
      category: "laptop",
      model: "Asus VivoBook S14",
      processor: "Intel Core i5",
      ram: "8GB",
      "video-card": "Intel UHD Graphics",
      "operating-sistem": "Windows 10",
      dimensions: "32.4 x 21.3 x 1.59 cm",
      weight: "1.4 kg",
      "battery-life": "Up to 12 hours",
      screen: "14-inch FHD display",
      warranty: "12 months",
      hardcore: "512GB",
      description: "The Asus VivoBook S14 is a lightweight and stylish laptop that is perfect for students and professionals on the go.",
      price: "$879"
    },
    {
      id: 28,
      category: "laptop",
      model: "Acer Predator Helios 300",
      processor: "Intel Core i7",
      ram: "16GB",
      "video-card": "NVIDIA GeForce RTX 3060",
      "operating-sistem": "Windows 10",
      dimensions: "35.9 x 25.5 x 2.39 cm",
      weight: "2.3 kg",
      "battery-life": "Up to 6 hours",
      screen: "15.6-inch FHD display",
      warranty: "12 months",
      hardcore: "1TB",
      description: "The Acer Predator Helios 300 is a gaming laptop that offers high-performance gaming and advanced cooling technology.",
      price: "$900"
    },
    {
      id: 29,
      category: "laptop",
      model: "Microsoft Surface Book 3",
      processor: "Intel Core i7",
      ram: "32GB",
      "video-card": "NVIDIA GeForce GTX 1660 Ti",
      "operating-sistem": "Windows 10",
      dimensions: "34.3 x 25.1 x 2.3 cm",
      weight: "1.64 kg",
      "battery-life": "Up to 17.5 hours",
      screen: "15-inch PixelSense display",
      warranty: "12 months",
      hardcore: "512GB",
      description: "The Microsoft Surface Book 3 is a powerful and versatile laptop that can be used as a tablet or a laptop.",
      price: "$1190"
    },
    {
      id: 30,
      category: "laptop",
      model: "Razer Blade Stealth 13",
      processor: "Intel Core i7",
      ram: "16GB",
      "video-card": "NVIDIA GeForce GTX 1650 Ti",
      "operating-sistem": "Windows 10",
      dimensions: "30.4 x 20.6 x 1.5 cm",
      weight: "1.41 kg",
      "battery-life": "Up to 13 hours",
      screen: "13.3-inch FHD display",
      warranty: "12 months",
      hardcore: "512GB",
      description: "The Razer Blade Stealth 13 is a compact and powerful laptop that is perfect for gaming and productivity.",
      price: "$2088"
    },
    {
      id: 31,
      category: "smartphone",
      model: "iPhone 13",
      processor: "A16 Bionic",
      ram: "6GB",
      "video-card": "Apple GPU",
      "operating-sistem": "iOS 17",
      dimensions: "14.32 x 6.71 x 0.71 cm",
      weight: "173 grams",
      "battery-life": "Up to 75 hours",
      screen: "6.1-inch Super Retina XDR, 1170 x 2532 pixels",
      warranty: "12 months",
      "Internal-memory": "128GB, 256GB, 512GB",
      description: "The iPhone 13 brings a new level of power and performance with its A16 Bionic chip and stunning Super Retina XDR display.",
      price: "$999",
      Camera: "12MP + 12MP dual rear cameras, 12MP front camera"
    },
    {
      id: 32,
      category: "smartphone",
      model: "Samsung Galaxy S22",
      processor: "Exynos 990",
      ram: "8GB",
      "video-card": "Mali-G77 MP11",
      "operating-sistem": "Android 13",
      dimensions: "15.04 x 7.14 x 0.79 cm",
      weight: "175 grams",
      "battery-life": "Up to 80 hours",
      screen: "6.2-inch Dynamic AMOLED 2X, 1080 x 2340 pixels",
      warranty: "12 months",
      "Internal-memory": "128GB, 256GB, 512GB",
      description: "The Samsung Galaxy S22 is a powerful Android smartphone with a stunning display and a versatile camera system.",
      price: "$899",
      Camera: "50MP + 12MP + 12MP triple rear cameras, 10MP front camera"
    },
    {
      id: 33,
      category: "smartphone",
      model: "Google Pixel 7",
      processor: "Qualcomm Snapdragon 895",
      ram: "6GB",
      "video-card": "Adreno 730",
      "operating-sistem": "Android 13",
      dimensions: "14.35 x 6.81 x 0.82 cm",
      weight: "168 grams",
      "battery-life": "Up to 72 hours",
      screen: "6.2-inch OLED, 1080 x 2400 pixels",
      warranty: "12 months",
      "Internal-memory": "128GB, 256GB",
      description: "The Google Pixel 7 is a high-end Android smartphone with an exceptional camera and a clean software experience.",
      price: "$799",
      Camera: "12.2MP + 16MP dual rear cameras, 8MP front camera"
    },
    {
      id: 34,
      category: "smartphone",
      model: "Huawei P60",
      processor: "HiSilicon Kirin 9000",
      ram: "8GB",
      "video-card": "Mali-G78 MP24",
      "operating-sistem": "HarmonyOS 3.0",
      dimensions: "15.32 x 7.23 x 0.89 cm",
      weight: "189 grams",
      "battery-life": "Up to 90 hours",
      screen: "6.4-inch OLED, 1080 x 2400 pixels",
      warranty: "12 months",
      "Internal-memory": "128GB, 256GB, 512GB",
      description: "The Huawei P60 is a flagship smartphone with a powerful processor and a stunning OLED display.",
      price: "$899",
      Camera: "50MP + 12MP + 8MP triple rear cameras, 32MP front camera"
    },
    {
      id: 35,
      category: "smartphone",
      model: "OnePlus 10",
      processor: "Qualcomm Snapdragon 898",
      ram: "8GB",
      video_card: "Adreno 730",
      operating_sistem: "OxygenOS 12",
      dimensions: "15.08 x 7.18 x 0.79 cm",
      weight: "180 grams",
      battery_life: "Up to 80 hours",
      screen: "6.5-inch Fluid AMOLED, 1080 x 2400 pixels",
      warranty: "12 months",
      Internal_memory: "128GB, 256GB, 512GB",
      description: "The OnePlus 10 is a premium Android smartphone with a powerful processor and a smooth 120Hz display.",
      price: "$899",
      Camera: "64MP + 12MP + 8MP triple rear cameras, 32MP front camera"
    },
    {
      id: 36,
      category: "smartphone",
      model: "Xiaomi Mi 12",
      processor: "Qualcomm Snapdragon 895",
      ram: "8GB",
      video_card: "Adreno 730",
      operating_sistem: "MIUI 13",
      dimensions: "15.21 x 7.17 x 0.81 cm",
      weight: "192 grams",
      battery_life: "Up to 85 hours",
      screen: "6.7-inch AMOLED, 1440 x 3200 pixels",
      warranty: "12 months",
      Internal_memory: "128GB, 256GB, 512GB",
      description: "The Xiaomi Mi 12 is a feature-packed Android smartphone with a high-resolution display and a powerful processor.",
      price: "$999",
      Camera: "108MP + 12MP + 8MP triple rear cameras, 32MP front camera"
    },
    {
      id: 37,
      category: "smartphone",
      model: "Sony Xperia 1 III",
      processor: "Qualcomm Snapdragon 888",
      ram: "12GB",
      video_card: "Adreno 660",
      operating_sistem: "Android 13",
      dimensions: "16.7 x 7.2 x 0.81 cm",
      weight: "186 grams",
      battery_life: "Up to 90 hours",
      screen: "6.5-inch OLED, 1644 x 3840 pixels",
      warranty: "12 months",
      Internal_memory: "256GB, 512GB",
      description: "The Sony Xperia 1 III is a flagship Android smartphone with a stunning 4K HDR OLED display and a versatile camera system.",
      price: "$1,299",
      Camera: "12MP + 12MP + 12MP triple rear cameras, 8MP front camera"
  },
  {
      id: 38,
      category: "smartphone",
      model: "LG G10",
      processor: "Qualcomm Snapdragon 898",
      ram: "8GB",
      video_card: "Adreno 730",
      operating_sistem: "Android 13",
      dimensions: "15.24 x 7.12 x 0.81 cm",
      weight: "183 grams",
      battery_life: "Up to 80 hours",
      screen: "6.3-inch OLED, 1080 x 2400 pixels",
      warranty: "12 months",
      Internal_memory: "128GB, 256GB, 512GB",
      description: "The LG G10 is a flagship Android smartphone with a sleek design and a powerful processor.",
      price: "$899",
      Camera: "48MP + 12MP + 8MP triple rear cameras, 16MP front camera"
  },
  {
      id: 39,
      category: "smartphone",
      model: "Motorola Edge 30",
      processor: "Qualcomm Snapdragon 898",
      ram: "8GB",
      video_card: "Adreno 730",
      operating_sistem: "Android 13",
      dimensions: "16.28 x 7.42 x 0.86 cm",
      weight: "198 grams",
      battery_life: "Up to 85 hours",
      screen: "6.8-inch OLED, 1440 x 3200 pixels",
      warranty: "12 months",
      Internal_memory: "128GB, 256GB, 512GB",
      description: "The Motorola Edge 30 is a premium Android smartphone with a large display and a powerful processor.",
      price: "$999",
      Camera: "108MP + 12MP + 8MP triple rear cameras, 32MP front camera"
  },
  {
      id: 40,
      category: "smartphone",
      model: "Nokia 10",
      processor: "Qualcomm Snapdragon 888",
      ram: "8GB",
      video_card: "Adreno 660",
      operating_sistem: "Android 13",
      dimensions: "16.45 x 7.72 x 0.89 cm",
      weight: "210 grams",
      battery_life: "Up to 95 hours",
      screen: "6.9-inch OLED, 1440 x 3200 pixels",
      warranty: "12 months",
      Internal_memory: "128GB, 256GB, 512GB",
      description: "The Nokia 10 is a flagship Android smartphone with a large OLED display and a powerful camera system.",
      price: "$1,199",
      Camera: "108MP + 12MP + 8MP triple rear cameras, 32MP front camera"
  },
  {
      id: 41,
      category: "smartphone",
      model: "Oppo Find X5",
      processor: "Qualcomm Snapdragon 898",
      ram: "8GB",
      video_card: "Adreno 730",
      operating_sistem: "ColorOS 13",
      dimensions: "16.5 x 7.8 x 0.89 cm",
      weight: "195 grams",
      battery_life: "Up to 90 hours",
      screen: "6.7-inch AMOLED, 1440 x 3200 pixels",
      warranty: "12 months",
      Internal_memory: "128GB, 256GB, 512GB",
      description: "The Oppo Find X5 is a high-end Android smartphone with a stunning display and a powerful processor.",
      price: "$1,099",
      Camera: "50MP + 12MP + 8MP triple rear cameras, 32MP front camera"
  },
  {
      id: 42,
      category: "smartphone",
      model: "Vivo X70 Pro",
      processor: "Qualcomm Snapdragon 888",
      ram: "8GB",
      video_card: "Adreno 660",
      operating_sistem: "Funtouch OS 12",
      dimensions: "16.4 x 7.2 x 0.86 cm",
      weight: "192 grams",
      battery_life: "Up to 95 hours",
      screen: "6.8-inch AMOLED, 1440 x 3200 pixels",
      warranty: "12 months",
      Internal_memory: "128GB, 256GB, 512GB",
      description: "The Vivo X70 Pro is a premium Android smartphone with a large AMOLED display and a versatile camera system.",
      price: "$1,199",
      Camera: "108MP + 12MP + 8MP triple rear cameras, 32MP front camera"
  },
  {
    id: 43,
    category: "headphone",
    model: "Sony WH-1000XM4",
    weight: "254",
    battery_life: "30",
    warranty: "12",
    description: "Industry-leading noise canceling with Dual Noise Sensor technology",
    price: "349.99",
    sound: "High-Resolution Audio",
    compatibility: "Bluetooth, NFC",
    connectivity: "Wireless",
    extra_functions: "Amazon Alexa, Google Assistant, touch control",
    waterproof: "No",
    touch_control: "Yes",
    microphone: "Yes"
},
{
    id: 44,
    category: "headphone",
    model: "Bose QuietComfort 35 II",
    weight: "235",
    battery_life: "20",
    warranty: "24",
    description: "Three levels of world-class noise cancellation for better listening experience",
    price: "299",
    sound: "Volume-optimized EQ",
    compatibility: "Bluetooth, NFC",
    connectivity: "Wireless",
    extra_functions: "Google Assistant, Alexa, touch control",
    waterproof: "No",
    touch_control: "Yes",
    microphone: "Yes"
},
{
    id: 45,
    category: "headphone",
    model: "Apple AirPods Pro",
    weight: "45.6",
    battery_life: "4.5",
    warranty: "12",
    description: "Active noise cancellation for immersive sound",
    price: "249",
    sound: "Adaptive EQ",
    compatibility: "Bluetooth",
    connectivity: "Wireless",
    extra_functions: "Siri, touch control",
    waterproof: "No",
    touch_control: "Yes",
    microphone: "Yes"
},
{
    id: 46,
    category: "headphone",
    model: "Jabra Elite 85t",
    weight: "7",
    battery_life: "25",
    warranty: "24",
    description: "Advanced noise-canceling earbuds for crystal-clear calls and music",
    price: "229.99",
    sound: "Customizable EQ",
    compatibility: "Bluetooth",
    connectivity: "Wireless",
    extra_functions: "Alexa, Siri, Google Assistant, touch control",
    waterproof: "Yes",
    touch_control: "Yes",
    microphone: "Yes"
},
{
    id: 47,
    category: "headphone",
    model: "Sennheiser Momentum 3 Wireless",
    weight: "305",
    battery_life: "17",
    warranty: "24",
    description: "Auto on/off and smart pause for seamless listening experience",
    price: "349.95",
    sound: "AptX, AAC",
    compatibility: "Bluetooth, NFC",
    connectivity: "Wireless",
    extra_functions: "Google Assistant, Alexa, touch control",
    waterproof: "No",
    touch_control: "Yes",
    microphone: "Yes"
},
{
    id: 48,
    category: "headphone",
    model: "Beats Solo Pro",
    weight: "267",
    battery_life: "22",
    warranty: "12",
    description: "Active noise cancellation and transparency mode for versatile use",
    price: "299.95",
    sound: "Apple's H1 chip, AAC",
    compatibility: "Bluetooth",
    connectivity: "Wireless",
    extra_functions: "Siri, touch control",
    waterproof: "No",
    touch_control: "Yes",
    microphone: "Yes"
},
{
  id: 49,
  category: "headphone",
  model: "Samsung Galaxy Buds Pro",
  weight: "6.3",
  battery_life: "8",
  warranty: "12",
  description: "Intelligent ANC and immersive sound for ultimate audio experience",
  price: "199.99",
  sound: "11mm woofer, 6.5mm tweeter",
  compatibility: "Bluetooth",
  connectivity: "Wireless",
  extra_functions: "Bixby, touch control",
  waterproof: "Yes",
  touch_control: "Yes",
  microphone: "Yes"
},
{
  id: 50,
  category: "headphone",
  model: "Anker Soundcore Life Q30",
  weight: "263",
  battery_life: "40",
  warranty: "18",
  description: "Hybrid active noise cancellation for optimal sound quality",
  price: "79.99",
  sound: "40mm drivers",
  compatibility: "Bluetooth",
  connectivity: "Wireless",
  extra_functions: "Google Assistant, touch control",
  waterproof: "No",
  touch_control: "Yes",
  microphone: "Yes"
},
{
  id: 51,
  category: "headphone",
  model: "JBL Quantum 800",
  weight: "410",
  battery_life: "14",
  warranty: "12",
  description: "Lossless 2.4GHz wireless for low latency gaming audio",
  price: "199.95",
  sound: "JBL QuantumSOUND Signature",
  compatibility: "Bluetooth, USB",
  connectivity: "Wireless",
  extra_functions: "Discord-certified, ANC, touch control",
  waterproof: "No",
  touch_control: "Yes",
  microphone: "Yes"
},
{
  id: 52,
  category: "headphone",
  model: "Plantronics BackBeat Pro 2",
  weight: "289",
  battery_life: "24",
  warranty: "24",
  description: "On-demand active noise canceling for immersive audio experience",
  price: "199.99",
  sound: "40mm drivers",
  compatibility: "Bluetooth",
  connectivity: "Wireless",
  extra_functions: "Open-listening mode, touch control",
  waterproof: "No",
  touch_control: "Yes",
  microphone: "Yes"
},
{
  id: 53,
  category: "headphone",
  model: "Razer Opus",
  weight: "265",
  battery_life: "25",
  warranty: "24",
  description: "Advanced active noise cancellation for uninterrupted audio",
  price: "199.99",
  sound: "40mm drivers",
  compatibility: "Bluetooth, NFC",
  connectivity: "Wireless",
  extra_functions: "Quick Attention Mode, touch control",
  waterproof: "No",
  touch_control: "Yes",
  microphone: "Yes"
},
{
  id: 54,
  category: "headphone",
  model: "Audio-Technica ATH-M50xBT",
  weight: "310",
  battery_life: "40",
  warranty: "12",
  description: "Critically acclaimed sonic performance with wireless convenience",
  price: "199",
  sound: "45mm drivers",
  compatibility: "Bluetooth",
  connectivity: "Wireless",
  extra_functions: "Touch control",
  waterproof: "No",
  touch_control: "Yes",
  microphone: "Yes"
},
    {
      id: 55,
      category: "headphone",
      model: "Marshall Monitor II A.N.C.",
      weight: "320",
      battery_life: "30",
      warranty: "24",
      description: "Active noise cancellation and custom-tuned drivers for exceptional audio",
      price: "319.99",
      sound: "40mm drivers",
      compatibility: "Bluetooth",
      connectivity: "Wireless",
      extra_functions: "Google Assistant, touch control",
      waterproof: "No",
      touch_control: "Yes",
      microphone: "Yes"
  },
  {
      id: 56,
      category: "headphone",
      model: "Panasonic RZ-S500W",
      weight: "7.5",
      battery_life: "6",
      warranty: "12",
      description: "Dual Hybrid Noise Cancelling for clear and immersive sound",
      price: "179.99",
      sound: "9mm drivers",
      compatibility: "Bluetooth",
      connectivity: "Wireless",
      extra_functions: "Touch control",
      waterproof: "Yes",
      touch_control: "Yes",
      microphone: "Yes"
  },
  {
      id: 57,
      category: "keyboard",
      model: "Corsair K95 RGB Platinum",
      weight: "1.31 kg",
      battery_life: "48 hours",
      warranty: "2 years",
      description: "Mechanical Gaming Keyboard",
      price: "$199.99",
      compatibility: "Windows 10, 8, 7",
      connectivity: "Wired USB",
      extra_functions: "Macro Keys, USB Passthrough",
      waterproof: "No",
      lights: "RGB Backlighting",
      dimensions: "46.5 x 17.1 x 3.6 cm",
      design: "Full Size",
      keycap_design: "Double-shot",
      media_keys: "Yes",
      wireless_range: "15 meters"
  },
  {
      id: 58,
      category: "keyboard",
      model: "Logitech G915",
      weight: "1.02 kg",
      battery_life: "30 hours",
      warranty: "2 years",
      description: "Wireless Mechanical Gaming Keyboard",
      price: "$249.99",
      compatibility: "Windows 10, 8.1, 8, 7",
      connectivity: "Wireless, Bluetooth, USB",
      extra_functions: "Programmable G-keys",
      waterproof: "No",
      lights: "RGB Backlighting",
      dimensions: "47.5 x 22.3 x 3.2 cm",
      design: "Full Size",
      keycap_design: "Low-profile",
      media_keys: "Yes",
      wireless_range: "10 meters"
  },
  {
      id: 59,
      category: "keyboard",
      model: "Razer Huntsman Elite",
      weight: "1.63 kg",
      battery_life: "50 hours",
      warranty: "2 years",
      description: "Opto-Mechanical Gaming Keyboard",
      price: "$199.99",
      compatibility: "Windows 10, 8, 7",
      connectivity: "Wired USB",
      extra_functions: "Multifunction Digital Dial, Magnetic Wrist Rest",
      waterproof: "No",
      lights: "RGB Backlighting",
      dimensions: "44.4 x 14.4 x 3.6 cm",
      design: "Full Size",
      keycap_design: "Doubleshot ABS",
      media_keys: "Yes",
      wireless_range: "15 meters"
  },
  {
      id: 60,
      category: "keyboard",
      model: "SteelSeries Apex Pro",
      weight: "0.77 kg",
      battery_life: "43 hours",
      warranty: "1 year",
      description: "Adjustable Mechanical Gaming Keyboard",
      price: "$199.99",
      compatibility: "Windows 10, 8, 7",
      connectivity: "Wired USB",
      extra_functions: "OLED Smart Display, Aircraft Grade Aluminum Frame",
      waterproof: "No",
      lights: "RGB Backlighting",
      dimensions: "43.7 x 13.9 x 4 cm",
      design: "Full Size",
      keycap_design: "Doubleshot ABS",
      media_keys: "Yes",
      wireless_range: "20 meters"
  },
  {
    id: 61,
    category: "keyboard",
    model: "Ducky One 2 Mini",
    weight: "0.59 kg",
    battery_life: "30 hours",
    warranty: "1 year",
    description: "60% Mechanical Gaming Keyboard",
    price: "$99.99",
    compatibility: "Windows 10, 8, 7",
    connectivity: "Wired USB",
    extra_functions: "N/A",
    waterproof: "No",
    lights: "RGB Backlighting",
    dimensions: "28.7 x 9.7 x 3.6 cm",
    design: "Compact",
    keycap_design: "Double-shot PBT",
    media_keys: "No",
    wireless_range: "10 meters"
},
{
    id: 62,
    category: "keyboard",
    model: "HyperX Alloy FPS Pro",
    weight: "0.9 kg",
    battery_life: "24 hours",
    warranty: "2 years",
    description: "Tenkeyless Mechanical Gaming Keyboard",
    price: "$69.99",
    compatibility: "Windows 10, 8.1, 8, 7",
    connectivity: "Wired USB",
    extra_functions: "N/A",
    waterproof: "No",
    lights: "Red Backlighting",
    dimensions: "35.6 x 13.5 x 3.8 cm",
    design: "Tenkeyless",
    keycap_design: "Doubleshot ABS",
    media_keys: "No",
    wireless_range: "10 meters"
},
{
    id: 63,
    category: "keyboard",
    model: "Corsair K70 RGB MK.2",
    weight: "1.25 kg",
    battery_life: "34 hours",
    warranty: "2 years",
    description: "Mechanical Gaming Keyboard",
    price: "$159.99",
    compatibility: "Windows 10, 8, 7",
    connectivity: "Wired USB",
    extra_functions: "Dedicated Volume and Multimedia Controls",
    waterproof: "No",
    lights: "RGB Backlighting",
    dimensions: "43.8 x 16.8 x 3.8 cm",
    design: "Full Size",
    keycap_design: "Doubleshot PBT",
    media_keys: "Yes",
    wireless_range: "11 meters"
},
{
    id: 64,
    category: "keyboard",
    model: "Razer BlackWidow V3 Pro",
    weight: "1.43 kg",
    battery_life: "38 hours",
    warranty: "2 years",
    description: "Wireless Mechanical Gaming Keyboard",
    price: "$229.99",
    compatibility: "Windows 10, 8, 7",
    connectivity: "Wireless, Bluetooth, USB",
    extra_functions: "Programmable Macro Keys, Magnetic Wrist Rest",
    waterproof: "No",
    lights: "RGB Backlighting",
    dimensions: "45.2 x 17.6 x 3.8 cm",
    design: "Full Size",
    keycap_design: "Doubleshot ABS",
    media_keys: "Yes",
    wireless_range: "25 meters"
},
{
    id: 65,
    category: "keyboard",
    model: "Logitech G213 Prodigy",
    weight: "1 kg",
    battery_life: "22 hours",
    warranty: "2 years",
    description: "RGB Gaming Keyboard",
    price: "$69.99",
    compatibility: "Windows 10, 8.1, 8, 7",
    connectivity: "Wired USB",
    extra_functions: "Integrated Palm Rest",
    waterproof: "Spill-Resistant",
    lights: "RGB Backlighting",
    dimensions: "45.2 x 21.8 x 3.3 cm",
    design: "Full Size",
    keycap_design: "Doubleshot ABS",
    media_keys: "Yes",
    wireless_range: "12 meters"
},
    {
      id: 66,
        category: "keyboard",
        model: "SteelSeries Apex 7 TKL",
        weight: "0.77 kg",
        battery_life: "48 hours",
        warranty: "1 year",
        description: "Tenkeyless Mechanical Gaming Keyboard",
        price: "$159.99",
        compatibility: "Windows 10, 8, 7",
        connectivity: "Wired USB",
        extra_functions: "OLED Smart Display, Aircraft Grade Aluminum Frame",
        waterproof: "No",
        lights: "RGB Backlighting",
        dimensions: "36.1 x 13.2 x 4 cm",
        design: "Tenkeyless",
        keycap_design: "Doubleshot ABS",
        media_keys: "Yes",
        wireless_range: "22 meters"
    }
  ];
 export default data; 